<?php

return [
    [
        'display' => 'Dashboard',
        'route' => 'admin.dashboard',
        'route_param' => null,
        'imag_path' => null,
        'target' => false,
        'icon' => 'bi bi-speedometer2',
        'sub_menus' => null,
        'can' => ['*'],
    ],
    [
        'display' => 'Banner',
        'route' => 'admin.banner.index',
        'route_param' => null,
        'imag_path' => null,
        'target' => false,
        'icon' => 'bi bi-card-image',
        'sub_menus' => null,
        'can' => ['Root'],
    ],
    [
        'display' => 'GoJoy',
        'route' => 'admin.gojoy.index',
        'route_param' => null,
        'imag_path' => null,
        'target' => false,
        'icon' => 'pi pi-heart',
        'sub_menus' => null,
        'can' => ['Root'],
    ],
    [
        'display' => 'Term And Conditions',
        'route' => 'admin.term-and-conditions.index',
        'route_param' => null,
        'imag_path' => null,
        'target' => false,
        'icon' => 'bi-filetype-doc',
        'sub_menus' => null,
        'can' => ['Root'],
    ],
    [
        'display' => 'Products',
        'route' => 'admin.product.index',
        'route_param' => null,
        'imag_path' => null,
        'target' => false,
        'icon' => 'bi bi-postcard-heart',
        'can' => ['Root'],
        'sub_menus' => [
            [
                'display' => 'Property Type',
                'route' => 'admin.property.type.index',
                'route_param' => null,
                'imag_path' => null,
                'target' => false,
                'icon' => 'bi bi-boxes',
                'sub_menus' => null,
                'can' => ['Root'],
            ],
        ],
    ],
    [
        'display' => 'Request Form(Inquery)',
        'route' => 'admin.request-form.lists',
        'route_param' => null,
        'imag_path' => null,
        'target' => false,
        'icon' => 'bi bi-send-exclamation',
        'can' => ['*'],
        'sub_menus' => [
            [
                'display' => 'Product Code Lists',
                'route' => 'admin.product-code-list.index',
                'route_param' => null,
                'imag_path' => null,
                'target' => false,
                'icon' => 'bi bi-list-stars',
                'sub_menus' => null,
                'can' => ['Root'],
            ],
            [
                'display' => 'Request Form Type',
                'route' => 'admin.request-form.type.index',
                'route_param' => null,
                'imag_path' => null,
                'target' => false,
                'icon' => 'bi-person-vcard',
                'sub_menus' => null,
                'can' => ['Root'],
            ],
        ],
    ],
    [
        'display' => 'E-Claim',
        'route' => 'admin.claim-case.index',
        'route_param' => null,
        'imag_path' => null,
        'target' => false,
        'icon' => 'bi bi-piggy-bank-fill',
        'can' => ['*'],
        'sub_menus' => [
            [
                'display' => 'Motor',
                'route' => 'admin.claim-case.motor',
                'route_param' => null,
                'imag_path' => null,
                'target' => false,
                'icon' => 'bi bi-car-front',
                'sub_menus' => null,
                'can' => ['*'],
            ],
            [
                'display' => 'Non Motor',
                'route' => 'admin.claim-case.non-motor',
                'route_param' => null,
                'imag_path' => null,
                'target' => false,
                'icon' => 'bi bi-collection',
                'sub_menus' => null,
                'can' => ['*'],
            ],
        ],
    ],
    [
        'display' => 'App Accounts',
        'route' => 'admin.customer.index',
        'route_param' => null,
        'imag_path' => null,
        'target' => false,
        'icon' => 'bi bi-people-fill',
        'can' => ['*'],
        'sub_menus' => [
            [
                'display' => 'Customer (Cor or Indi)',
                'route' => 'admin.customer.filter.by-type',
                'route_param' => 'INDIVIDUAL',
                'imag_path' => null,
                'target' => false,
                'icon' => 'bi bi-phone-fill',
                'can' => ['HR', 'Root'],
                'sub_menus' => null,
            ],
            [
                'display' => 'Employee',
                'route' => 'admin.customer.filter.by-type',
                'route_param' => 'EMPLOYEE',
                'imag_path' => null,
                'target' => false,
                'icon' => 'bi bi-person-vcard-fill',
                'can' => ['HR', 'Root'],
                'sub_menus' => null,
            ],
            [
                'display' => 'Agent',
                'route' => 'admin.customer.filter.by-type',
                'route_param' => 'AGENT',
                'imag_path' => null,
                'target' => false,
                'icon' => 'bi bi-shop-window',
                'can' => ['Agent', 'Root'],
                'sub_menus' => null,
            ],
            [
                'display' => 'Group (Risk Level)',
                'route' => 'admin.customer.filter.by-type',
                'route_param' => 'GROUP',
                'imag_path' => null,
                'target' => false,
                'icon' => 'bi bi-people-fill',
                'can' => ['HR', 'Root', 'Corporate'],
                'sub_menus' => null,
            ],
        /** [
                'display' => 'SMS Pool',
                'route' => 'admin.customer.pool',
                'route_param' => "GROUP",
                'imag_path' => null,
                'target' => false,
                'icon' => 'bi bi-database-fill-exclamation',
                'can' => ['HR', 'Root'],
                'sub_menus' => null,
            ],
         **/
        ],
    ],
    [
        'display' => 'Agent',
        'route' => 'admin.leaderboard.index',
        'route_param' => null,
        'imag_path' => null,
        'target' => false,
        'icon' => 'bi bi-shop-window',
        'can' => ['Agent', 'Root'],
        'sub_menus' => [
            [
                'display' => 'LeaderBoard',
                'route' => 'admin.leaderboard.index',
                'route_param' => null,
                'imag_path' => null,
                'target' => true,
                'icon' => 'bi bi-trophy-fill',
                'sub_menus' => null,
                'can' => ['Agent', 'Root'],
            ],
            [
                'display' => 'Training Resources',
                'route' => 'admin.training-resource.index',
                'route_param' => null,
                'imag_path' => null,
                'target' => true,
                'icon' => 'bi bi-book-half',
                'sub_menus' => null,
                'can' => ['Agent', 'Root'],
            ],
            [
                'display' => 'Agent Noti',
                'route' => 'admin.messaging.agent-history',
                'route_param' => null,
                'imag_path' => null,
                'target' => true,
                'icon' => 'bi bi-bell-fill',
                'sub_menus' => null,
                'can' => ['Agent', 'Root'],
            ],
        ],
    ],
    [
        'display' => 'Messaging',
        'route' => 'admin.messaging.index',
        'route_param' => null,
        'imag_path' => null,
        'target' => false,
        'icon' => 'bi bi-bell-fill',
        'can' => ['*'],
        'sub_menus' => [
            [
                'display' => 'Send noti to mutil user',
                'route' => 'admin.messaging.multicast.show-form-by-phone',
                'route_param' => null,
                'imag_path' => null,
                'target' => false,
                'icon' => 'bi bi-send-check-fill',
                'sub_menus' => null,
                'can' => ['*'],
            ],
            [
                'display' => 'Recent Message',
                'route' => 'admin.messaging.history',
                'route_param' => null,
                'imag_path' => null,
                'target' => false,
                'icon' => 'bi bi-clock-history',
                'sub_menus' => null,
                'can' => ['*'],
            ],
        ],
    ],
    [
        'display' => 'Location Map',
        'route' => 'admin.location-map.index',
        'route_param' => null,
        'imag_path' => null,
        'target' => false,
        'icon' => 'bi bi-geo-alt-fill',
        'can' => ['Root'],
        'sub_menus' => [
            [
                'display' => 'Category',
                'route' => 'admin.location-map-category.index',
                'route_param' => null,
                'imag_path' => null,
                'target' => false,
                'icon' => 'bi bi-map-fill',
                'sub_menus' => null,
                'can' => ['Root'],
            ],
        ],
    ],
    [
        'display' => 'Admin Acounts',
        'route' => 'admin.account.index',
        'route_param' => null,
        'imag_path' => null,
        'target' => false,
        'icon' => 'bi bi-person-circle',
        'can' => ['Root'],
        'sub_menus' => [
            [
                'display' => 'IAM',
                'route' => 'admin.iam.roles',
                'route_param' => null,
                'imag_path' => null,
                'target' => true,
                'icon' => 'bi bi-clipboard-check-fill',
                'sub_menus' => null,
                'can' => ['Root'],
            ],
        ],
    ],
    [
        'display' => 'LogsWatch',
        'route' => 'dev.logs.file.all',
        'route_param' => null,
        'imag_path' => null,
        'target' => false,
        'icon' => 'bi bi-file-earmark-medical-fill',
        'can' => ['Root'],
        'sub_menus' => [
            [
                'display' => 'App Logs',
                'route' => 'dev.logs.file.all',
                'route_param' => null,
                'imag_path' => null,
                'target' => true,
                'icon' => 'bi bi-file-earmark-medical-fill',
                'sub_menus' => null,
                'can' => ['Root'],
            ],
            [
                'display' => 'Admin Logs',
                'route' => 'admin.dashboard.logs.admin',
                'route_param' => null,
                'imag_path' => null,
                'target' => true,
                'icon' => 'bi bi-file-earmark-medical-fill',
                'sub_menus' => null,
                'can' => ['Root'],
            ],
        ],
    ],
    [
        'display' => 'Dev Operation',
        'route' => 'dev.doc.index',
        'route_param' => null,
        'imag_path' => null,
        'target' => true,
        'icon' => 'bi bi-code-slash',
        'can' => ['Root'],
        'sub_menus' => [
            [
                'display' => 'Agent Query Situation',
                'route' => 'dev.agent-query-situation',
                'route_param' => null,
                'imag_path' => null,
                'target' => true,
                'icon' => 'bi bi-database-fill-gear',
                'sub_menus' => null,
                'can' => ['Root'],
            ],
            [
                'display' => 'Mysql Query Situation',
                'route' => 'dev.mysql-query-situation',
                'route_param' => null,
                'imag_path' => null,
                'target' => true,
                'icon' => 'bi bi-database-fill-gear',
                'sub_menus' => null,
                'can' => ['Root'],
            ],
            [
                'display' => 'Setting',
                'route' => 'admin.settings.index',
                'route_param' => null,
                'imag_path' => null,
                'target' => true,
                'icon' => 'bi bi-gear-fill',
                'sub_menus' => null,
                'can' => ['Root'],
            ],
            [
                'display' => 'ENV Value',
                'route' => 'dev.show-env-value',
                'route_param' => null,
                'imag_path' => null,
                'target' => true,
                'icon' => 'bi bi-columns-gap',
                'sub_menus' => null,
                'can' => ['Root'],
            ],
            [
                'display' => 'One Click Deployment',
                'route' => 'dev.code.one-click-deploy',
                'route_param' => null,
                'imag_path' => null,
                'target' => true,
                'icon' => 'bi bi-rocket',
                'sub_menus' => null,
                'can' => ['Root'],
            ],
            [
                'display' => 'Terminal',
                'route' => 'dev.terminal',
                'route_param' => null,
                'imag_path' => null,
                'target' => true,
                'icon' => 'bi bi-terminal',
                'sub_menus' => null,
                'can' => ['Root'],
            ],
            [
                'display' => 'REST API',
                'route' => 'dev.doc.index',
                'route_param' => null,
                'imag_path' => null,
                'target' => true,
                'icon' => 'bi-filetype-doc',
                'sub_menus' => null,
                'can' => ['Root'],
            ],
            [
                'display' => 'Backup',
                'route' => 'dev.backup.database.show_backup_file',
                'route_param' => null,
                'imag_path' => null,
                'target' => false,
                'icon' => 'bi bi-database-fill-down',
                'sub_menus' => null,
                'can' => ['Root'],
            ],
        ],
    ],
];
